name: "sample"
replicaCount: 1

ingressController: nginx

service:
  type: ClusterIP

domainName: "docs.trader4.net"

tls:
  enabled: false
  secretName: docs-trader4-net-wildcard-tls

image:
  repository: "trader4.{{ .Values.name }}-docs"
  pullPolicy: Always
  tag: latest

resources: {}
tolerations: {}
